name: Subscription-based subreddit analysis

on:
  # schedule:
  #   # runs once a day at 04:17 UTC / 06:17 Finnish time
  #   - cron: '17 4 * * *'
  workflow_dispatch:

jobs:
  run-subscriptions-pipeline:
    runs-on: ubuntu-latest
    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      ATLAS_CONNECTION_STR: ${{ secrets.ATLAS_CONNECTION_STR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_ml.txt
      - name: Download NLTK data
        run: python -m nltk.downloader punkt punkt_tab vader_lexicon
      - name: Check inactive users and subscriptions
        run: python -m scripts.check_inactive_users
      - name: Run pipeline for posts analysis
        run: python -m scripts.subscriptions_pipeline --posts
      - name: Run pipeline for topics analysis
        run: python -m scripts.subscriptions_pipeline --topics